name: Update Fuel Prices and Graphs

on:
  schedule:
    - cron: "0 1 * * *" # Runs daily at 01:00 UTC; adjust as needed
  workflow_dispatch: # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp asyncio aiofiles matplotlib

      # Step 4: Run Dump Fuel Prices Script
      - name: Run Dump Fuel Prices Script
        env:
          AUTH_TOKEN_PROD: ${{ secrets.AUTH_TOKEN_PROD }}
        run: |
          python dump_fuelprices.py

      # Step 5: Generate Graphs
      - name: Generate Graphs
        run: |
          python graph.py

      # Step 6: Move site mappings and graphs to `docs/`
      - name: Move Site Mappings and Graphs
        run: |
          mkdir -p docs/graphs/
          cp fuelprices/site_mappings.json docs/
          cp -r graphs/* docs/graphs/

      # Step 7: Commit and push changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update fuel prices, site mappings, and graphs"
          git push origin main
