name: Update Fuel Prices and Graphs

on:
  schedule:
    - cron: "0 1 * * *" # Runs daily at 01:00 UTC; adjust as needed
  workflow_dispatch: # Allows manual trigger

jobs:
  update-fuelprices:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp asyncio aiofiles matplotlib

      # Step 4: Create Necessary Directories
      - name: Create Necessary Directories
        run: |
          mkdir -p docs/graphs
          mkdir -p graphs

      # Step 5: Run Dump Fuel Prices Script
      - name: Run Dump Fuel Prices Script
        run: python dump_fuelprices.py

      # Step 6: Run Graph Script
      - name: Run Graph Script
        run: python graph.py

      # Step 7: Copy Graphs to GitHub Pages Directory
      - name: Copy Graph Files to Docs
        run: |
          if [ "$(ls -A graphs)" ]; then
            cp -r graphs/* docs/graphs
          else
            echo "No graphs generated."
          fi

      # Step 8: Commit and Push Changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated fuel prices and graphs as of $(date '+%Y-%m-%d %H:%M:%S %Z')"
          git push origin main
