name: Update Fuel Prices and Graphs

on:
  schedule:
    - cron: "0,30 * * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  update-fuelprices:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Specify the Python version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r aiohttp asyncio aiofiles matplotlib

      # Step 4: Run the dump_fuelprices.py script
      - name: Run Dump Fuel Prices Script
        run: python dump_fuelprices.py

      # Step 5: Run the graph.py script
      - name: Run Graph Script
        run: python graph.py

      # Step 6: Copy files to GitHub Pages directory
      - name: Copy Files to GitHub Pages
        run: |
          mkdir -p docs/graphs
          cp -r graphs/* docs/graphs
          cp index.html docs/


      # Step 7: Commit and push changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: Australia/Adelaide
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "updated fuel prices as of $(date '+%Y-%m-%d %H:%M:%S %Z')"
          git push origin main
